dates:
  2023: September 23, 2023
  2024: September 20, 2024
  2025: September 19, 2025
race_dist: 100K
race_loc: "Natural Chimneys Park, VA"
race_name: Grindstone
race_uris:
  2023: 37038.grindstonetrailrunningfestivalbyutmb100k
  2024: 37038.grindstonetrailrunningfestivalbyutmb100k
  2025: 37038.grindstonetrailrunningfestivalbyutmb100k