dates:
  2023: September 30, 2023
  2024: October 4, 2024
  2025: September 27, 2025
race_dist: 100K
race_loc: "Roubion, France"
race_name: Nice Cote D'Azur
race_uris:
  2023: 32444.nicecoted-azurbyutmb-roubion-nice100k
  2024: 32444.nicecoted-azurbyutmb-roubion-nice-100k
  2025: 32444.nicecoted-azurbyutmb-roubion-nice-100k