dates:
  2024: March 23, 2024
  2025: March 22, 2025
race_dist: 120K
race_loc: Radda in Chianti, Italy
race_name: Ultra Trail Chianti Castles (UTCC)
race_uris:
  2024: 29669.chiantiultratrailbyutmb-ultratrailchianticastles
  2025: 29669.chiantiultratrailbyutmb-ultratrailchianticastles
