dates:
  2020: February 8, 2020
  2021: February 13, 2021
  2023: February 11, 2023
  2024: February 17, 2024
  2025: February 15, 2025
race_dist: 100K
race_loc: Rotorua, New Zealand
race_name: Tarawera 100K
race_uris:
  2020: 895.taraweraultramarathon102km
  2021: 895.taraweraultramarathon102km
  2023: 895.taraweraultramarathonbyutmb-tum102
  2024: 895.taraweraultra-trailbyutmb-t102
  2025: 895.taraweraultra-trailbyutmb-t102
